[package]
name = "jsoup"
edition = "2024"


[[bin]]
name = "jsoup"
path = "src/main.rs"

[lib]
path = "src/lib.rs"

[dependencies]
serde_json = "1.0.140"

[dev-dependencies]
pretty_assertions = "1.4.1"
