[workspace]
members = [".", "fuzz"]
resolver = "2"

[package]
name = "jsoup"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
serde_json = "1.0.140"

[dev-dependencies]
pretty_assertions = "1.4.1"
